config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :articles do
    resources :comments, only: [:create, :new]
  end
  resources :users, only: [:show]
  namespace :api do
    resources :articles, only: [:index], defaults: {format: 'json'}
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: true
  validates :body, presence: true
  validates :public, presence: true
  validates :user, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :name, presence: true

  has_many :articles
  has_many :comments
end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < ApplicationController

  def index
    @articles = Article.where(public: 1).where('title LIKE(?)', "%#{params[:keyword]}%").order('id DESC')
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.where(public: 1).order('created_at DESC').page(params[:page]).per(10)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
  end

  def show

    @article = Article.find_by(id: params[:id])
    if @article == nil
      flash[:fail] = "削除されています"
      redirect_to root_path
      return
    end

    if user_signed_in?
      if @article.user.id != current_user.id && @article.public == 0
        flash[:fail] = "投稿者によって非公開に設定されています"
        redirect_to root_path
      end
    else
      if @article.public == 0
        flash[:fail] = "投稿者によって非公開に設定されています"
      redirect_to root_path
      end
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    article = Article.find(params[:id])
    article.update(article_params)
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :public).merge(user_id: current_user.id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    
  end
  def create
    @comment = Comment.create(comment_params)
  end
  private
  def comment_params
    params.permit(:comment, :article_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(current_user.id)
    @articles = current_user.articles.order('created_at DESC').page(params[:page]).per(10)
  end
end

app/helpers/api/messages_helper.rb
module Api::MessagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_checked_article.html.erb
<div id="app">
  <div class="checked_article_list">
  <div class="checked_article_list__title">最近見たページ</div>
  <div class="checked_article_list__item" v-for="page in pages">
  <a v-bind:href="page.url">{{page.title}}</a>
  </div>
  </div>
</div>

app/views/articles/create.html.erb
<div class="container">
<div class="back_to_top">
  <p>投稿が完了しました</p>
  <%= link_to 'トップへ戻る', root_path, class: "back_to_top__button" %>
</div>
  </div>

app/views/articles/destroy.html.erb
<div class="container">
<div class="back_to_top">
<p>削除が完了しました</p>
<%= link_to 'トップへ戻る', root_path, class: "back_to_top__button" %>
</div>
  </div>

app/views/articles/edit.html.erb
<div class="container">
<div class="edit_article_area">
<p><%= form_for (@article) do |f| %></p>
<p>メモを編集してください</p>
<p><%= f.label :title, "タイトル："%><%= f.text_field :title, placeholder: "必須",  value: @article.title, required: true %></p>
<p><%= f.label :body, "本文"%></p>
<p><%= f.text_area :body, placeholder: "必須",  value: @article.body, required: true %></p>
<p><%= f.label :public, "公開する"%><%= f.check_box :public, {}, 1, 0 %></p>
<p><%= f.submit "送信", method: :patch, class: "article_submit_button" %></p>
<% end %>
</div>
  </div>

app/views/articles/index.html.erb
<p class="flash"><%= flash[:fail] %></p>
<%= render "checked_article.html.erb" %>
<div class="container">
  <p class="articles_view">＜みんなの投稿＞</p>
  <form class="search_form">
    <label for="search">
      <%= fa_icon("search") %>
    </label>
    <input type="text" id="search" placeholder="メモのタイトルを入力して検索">
  </form>
  <ul class="article_list" >
    <% @articles.each do |article| %>
      <li class="article">
        <div class="article__title">
          <%= link_to article.title, article_path(article.id) %>
        </div>
        <p><%= article.user.name %>さんの投稿</p>
      </li>
    <% end %>
  </ul>
  <%= paginate @articles %>
</div>

app/views/articles/new.html.erb
<div class="container">
<div class="new_article_page">
<%= form_for (@article) do |f| %>
  <p>メモを書いて投稿してください</p>
  <p><%= f.label :title, "タイトル："%><%= f.text_field :title, placeholder: "必須",  required: true %></p>
  <p><%= f.label :body, "本文"%></p>
  <p><%= f.text_area :body, placeholder: "必須",  required: true %></p>
  <p><%= f.label :public, "公開する"%><%= f.check_box :public, {}, 1, 0 %></p>
  <p><%= f.submit "投稿する", class: "article_submit_button"%></p>
<% end %>
</div>
  </div>

app/views/articles/show.html.erb
<%= render "checked_article.html.erb" %>
<div class="container">
<p class="writer"><%= @article.user.name %>さんの投稿</p>
<h2 class="article_show_title"><%= @article.title %></h1>
<div class="article_area"><%= simple_format(h(@article.body) )%></div>

<% if user_signed_in? && @article.user.id == current_user.id %>
  <div class="select_area">
    <%= link_to edit_article_path(@article.id) do %>
    <div class="select_area__button">編集</div>
    <% end %>

    <%= link_to article_path(@article.id), method: :delete, id: "delete" do %>
    <div class="select_area__button">削除</div>
    <% end %>
  </div>
<% end %>
</div>

app/views/articles/update.html.erb
<div class="container">
<div class="back_to_top">
<p>送信が完了しました</p>
<%= link_to 'トップへ戻る', root_path, class: "back_to_top__button" %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>プロメモ</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%# <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> %>
  <script src="https://cdn.jsdelivr.net/npm/vue"></script>

  </head>

  <body>
  
  <header>
    <div class="header">
        <%= link_to "プロメモ", root_path, class: "header_title"%>
      <div class="header_button">
        <%= link_to new_article_path, class: "header_button_post_icon"  do %>
          <%= fa_icon("edit") %>
        <% end %>
        <%= link_to "投稿する", new_article_path, class: "header_button_post" %>
        <div class="header_button_user">
          <% if user_signed_in? %>
            <%= current_user.name %>さん
          <% else %>
            ようこそゲストさん
          <% end %>
          <%= fa_icon("caret-down") %>
          <div class="menu">
              <% if user_signed_in? %>
                <%= link_to 'マイページ', user_path(current_user.id) %>
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
              <% else %>
                <%= link_to '新規登録',new_user_registration_path %>
                <%= link_to 'ログイン', new_user_session_path %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </header>
  
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<%= render "/articles/checked_article.html.erb" %>
<div class="container user_page">
  <div class="user_page__title">
      <%= link_to edit_user_registration_path do %>
      <div class="link_to_edit_user">登録情報の編集</div>
      <% end %>
      <h2><%= @user.name %>さんのページ</h2>
  </div>
  <p class="users_articles">＜投稿したメモ一覧＞</p>
  <ul class="article_list" >
    <% @articles.each do |article| %>
    <li class="article"><div class="article__title"><%= link_to article.title, article_path(article.id) %></div></li>
    <% end %>
    <%= paginate(@articles) %>
  </ul>
</div>